version: '3'
x-spark-common: &spark-common
  image: bitnami/spark:latest
  volumes:
    - ./resource:/opt/bitnami/spark/resource
    - ./jobs:/opt/bitnami/spark/jobs
  networks:
    - confluent
services:
  spark-master:
    <<: *spark-common
    image: bitnami/spark:latest
    command: bin/spark-class org.apache.spark.deploy.master.Master
    hostname: spark-master
    container_name: spark-master
    ports:
      - "9090:8080"
      - "7077:7077"
    networks:
      - confluent
  spark-worker:
    <<: *spark-common
    image: bitnami/spark:latest
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    container_name: spark-worker
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1g
      SPARK_MASTER_URL: spark://spark-master:7077
    networks:
      - confluent
networks:
  confluent:
